drop table if exists item_domain CASCADE 
drop table if exists list_domain CASCADE 
create table item_domain (id bigint generated by default as identity, complete_by varchar(255), complete_status boolean, description varchar(255), list_id bigint, primary key (id))
create table list_domain (id bigint generated by default as identity, title varchar(255), primary key (id))
alter table item_domain add constraint FK7bd6c1m54dykyciyrqdnb7htg foreign key (list_id) references list_domain on delete cascade